# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'docker-con-azure-reg'
    repository: 'build1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks'
    namespace: 'default'
    command: 'apply'
    arguments: 'deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Pay-As-You-Go(1)(e0b04bb4-2704-41a6-894f-a1032232638a)'
    azureContainerRegistry: 'dockerapppipe.azurecr.io'
    secretName: 'acr-secret'